"use client";

import { useEffect } from "react";
import { AlertTriangle, Sparkles, Wallet } from "lucide-react";
import { Card, SectionHeader } from "@/components/shared/SharedComponents";
import { AITrust } from "@/components/shared/AITrust";
import { useTravelGenerator } from "@/hooks/useAI";
import { checklistProgress, type ItineraryDay, type TravelChecklist } from "@/lib/ai";
import { mockFamilyMembers, mockTravelPlans } from "@/lib/mock-data";

const checklistLabels: { key: keyof TravelChecklist; label: string }[] = [{ key: "documents", label: "📄 证件" }, { key: "clothing", label: "👔 衣物" }, { key: "kids", label: "👶 儿童" }, { key: "other", label: "🎒 其他" }];

export default function TravelPlan() {
  const plan = mockTravelPlans[0];
  const { data: draft, generate, loading, source, degraded, reasons } = useTravelGenerator();
  useEffect(() => { if (plan) void generate({ destination: plan.destination, startDate: plan.start_date, endDate: plan.end_date, travelers: mockFamilyMembers, budget: plan.budget, pace: "balanced" }); }, [generate, plan]);
  if (!plan) return <div className="py-12 text-center"><div className="mb-3 text-4xl">✈️</div><div className="text-slate-500">还没有旅行计划，创建一个吧</div></div>;
  const itinerary = (draft?.itinerary ?? plan.itinerary) as { days: ItineraryDay[]; tips: string[] };
  const checklist = (draft?.checklist ?? plan.checklist) as TravelChecklist;
  const progress = checklistProgress(checklist);
  const days = draft?.days ?? itinerary.days.length;
  return <div className="space-y-6"><SectionHeader title="旅行计划" subtitle="本地规则先生成完整骨架，AI 仅增强行程内容。" action={<button onClick={() => void generate({ destination: plan.destination, startDate: plan.start_date, endDate: plan.end_date, travelers: mockFamilyMembers, budget: plan.budget, pace: "balanced" })} disabled={loading} className="flex items-center gap-1.5 rounded-xl bg-sky-600 px-3 py-2 text-xs font-semibold text-white hover:bg-sky-700 disabled:opacity-60"><Sparkles size={14} className={loading ? "animate-spin" : ""} />{loading ? "生成中" : "AI 优化行程"}</button>} />
    <Card className="overflow-hidden bg-gradient-to-r from-sky-600 to-violet-600 text-white"><div className="p-6"><div className="text-sm text-white/75">即将出行</div><div className="mt-1 text-3xl font-bold">{draft?.destination ?? plan.destination}</div><div className="mt-1 text-sm text-white/80">{plan.start_date} ~ {plan.end_date} · {days} 天</div><div className="mt-5 flex items-center gap-4"><div><div className="text-4xl font-bold">{progress.pct}%</div><div className="text-sm text-white/75">准备完成度</div></div><div className="flex-1"><div className="h-2 overflow-hidden rounded-full bg-white/20"><div className="h-full rounded-full bg-white transition-all" style={{ width: `${progress.pct}%` }} /></div><div className="mt-1 text-xs text-white/70">已完成 {progress.done} / {progress.total} 项</div></div></div>{plan.budget && <div className="mt-4 text-sm text-white/80">预算 ¥{plan.budget.toLocaleString()}</div>}</div></Card><AITrust source={source} degraded={degraded} reasons={reasons} />
    {draft?.warnings.length ? <div className="space-y-2">{draft.warnings.map((warning) => <div key={warning} className="flex gap-2 rounded-xl border border-amber-200 bg-amber-50 p-3 text-xs leading-5 text-amber-800 dark:border-amber-500/30 dark:bg-amber-500/10 dark:text-amber-200"><AlertTriangle size={15} className="shrink-0" />{warning}</div>)}</div> : null}
    {draft?.budgetBreakdown && <Card><div className="flex items-center gap-2 border-b border-slate-100 p-4 dark:border-slate-800"><Wallet size={16} className="text-sky-600" /><h2 className="text-sm font-semibold text-slate-900 dark:text-white">预算拆分</h2>{draft.perPersonPerDay != null && <span className="ml-auto text-xs text-slate-500">人均每天 ¥{draft.perPersonPerDay.toLocaleString()}</span>}</div><div className="grid grid-cols-2 gap-3 p-4 sm:grid-cols-5">{draft.budgetBreakdown.map((item) => <div key={item.label} className="rounded-xl bg-slate-50 p-3 dark:bg-slate-800"><div className="text-xs text-slate-500">{item.label}</div><div className="mt-1 text-sm font-semibold text-slate-900 dark:text-white">¥{item.amount.toLocaleString()}</div><div className="mt-1 text-[10px] text-slate-400">{item.pct}%</div></div>)}</div></Card>}
    <div className="grid gap-6 lg:grid-cols-2"><Card><div className="border-b border-slate-100 p-4 dark:border-slate-800"><h2 className="text-sm font-semibold text-slate-900 dark:text-white">AI 行程规划</h2></div><div className="space-y-4 p-4">{itinerary.days.map((day) => <div key={day.day} className="rounded-xl bg-slate-50 p-3 dark:bg-slate-800"><div className="mb-2 flex items-center gap-2"><span className="grid h-5 w-5 place-items-center rounded-full bg-sky-600 text-xs font-bold text-white">{day.day}</span><span className="text-sm font-medium text-slate-900 dark:text-white">{day.title}</span>{day.area && <span className="ml-auto text-[10px] text-slate-400">{day.area}</span>}</div><div className="ml-7 space-y-1">{day.activities.map((activity) => <div key={activity} className="flex items-center gap-2 text-sm text-slate-600 dark:text-slate-400"><span className="h-1 w-1 rounded-full bg-slate-300" />{activity}</div>)}</div>{day.note && <p className="ml-7 mt-2 text-xs text-slate-400">{day.note}</p>}</div>)}{itinerary.tips.length > 0 && <div className="rounded-xl border border-sky-100 bg-sky-50 p-3 text-xs leading-5 text-sky-800 dark:border-sky-500/20 dark:bg-sky-500/10 dark:text-sky-200">{itinerary.tips.map((tip) => <p key={tip}>• {tip}</p>)}</div>}</div></Card>
      <Card><div className="border-b border-slate-100 p-4 dark:border-slate-800"><h2 className="text-sm font-semibold text-slate-900 dark:text-white">行李清单</h2></div><div className="space-y-4 p-4">{checklistLabels.map(({ key, label }) => <div key={key}><h3 className="mb-2 text-xs font-medium text-slate-500">{label}</h3><div className="space-y-1.5">{checklist[key].map((item) => <label key={item.name} className="flex items-center gap-2"><input type="checkbox" checked={item.done} readOnly className="rounded border-slate-300 text-sky-500" /><span className={`text-sm ${item.done ? "text-slate-400 line-through" : "text-slate-700 dark:text-slate-300"}`}>{item.name}</span></label>)}</div></div>)}</div></Card></div></div>;
}
