"use client";

import { useState } from "react";
import { AlertTriangle, Plus, RefreshCw, Sparkles } from "lucide-react";
import { SectionHeader, Card, Badge } from "@/components/shared/SharedComponents";
import { AITrust } from "@/components/shared/AITrust";
import { useOutfitRecommendation } from "@/hooks/useAI";
import { useOutfitsData, useWardrobeData } from "@/hooks/useData";
import { DataError, DemoBanner } from "@/components/shared/DataStates";

const typeLabels: Record<string, string> = { top: "上衣", bottom: "下装", outerwear: "外套", dress: "连衣裙", shoes: "鞋子", accessory: "配饰" };
const occasions = [{ value: "work", label: "通勤" }, { value: "casual", label: "休闲" }, { value: "sport", label: "运动" }, { value: "formal", label: "正式" }] as const;
const iconFor = (type: string) => type === "top" ? "👕" : type === "bottom" ? "👖" : type === "outerwear" ? "🧥" : type === "shoes" ? "👟" : "👔";

export default function WardrobePage() {
  const [occasion, setOccasion] = useState<(typeof occasions)[number]["value"]>("casual");
  const wardrobe = useWardrobeData(); const outfits = useOutfitsData();
  const mockWardrobeItems = wardrobe.items;
  const { current, next, enhance, loading, source, degraded, reasons } = useOutfitRecommendation(wardrobe.items, { temperature: 32, weather: "晴", occasion });
  return <div className="space-y-6"><SectionHeader title="智能穿搭" subtitle={`衣柜共 ${wardrobe.items.length} 件 · 依据天气、场合和单品协调度生成`} action={<button className="flex items-center gap-2 rounded-xl bg-sky-600 px-3 py-2 text-xs font-semibold text-white hover:bg-sky-700"><Plus size={14} />添加衣物</button>} /><DemoBanner isDemo={wardrobe.isDemo} /><DataError error={wardrobe.error ?? outfits.error} onRetry={() => void Promise.all([wardrobe.refresh(), outfits.refresh()])} />
    <div className="flex flex-wrap gap-2" role="tablist" aria-label="穿搭场合">{occasions.map((item) => <button key={item.value} role="tab" aria-selected={occasion === item.value} onClick={() => setOccasion(item.value)} className={`rounded-full px-3 py-1.5 text-xs font-medium transition ${occasion === item.value ? "bg-sky-600 text-white" : "bg-slate-100 text-slate-600 dark:bg-slate-800 dark:text-slate-400"}`}>{item.label}</button>)}</div>
    <Card><div className="flex items-center justify-between border-b border-slate-100 p-4 dark:border-slate-800"><div><h2 className="text-sm font-semibold text-slate-900 dark:text-white">今日穿搭推荐</h2><p className="mt-1 text-xs text-slate-500">晴 · 32°C · {occasions.find((item) => item.value === occasion)?.label}</p></div><div className="flex gap-1"><button onClick={next} disabled={!current} className="flex items-center gap-1 rounded-lg px-2 py-1.5 text-xs text-sky-700 hover:bg-sky-50 disabled:opacity-50 dark:text-sky-300 dark:hover:bg-sky-500/10"><RefreshCw size={14} />换一套</button><button onClick={() => void enhance()} disabled={loading} className="flex items-center gap-1 rounded-lg px-2 py-1.5 text-xs text-violet-700 hover:bg-violet-50 disabled:opacity-50 dark:text-violet-300 dark:hover:bg-violet-500/10"><Sparkles size={14} className={loading ? "animate-spin" : ""} />AI 分析</button></div></div><div className="p-4">{current ? <><div className="grid grid-cols-2 gap-3 sm:grid-cols-3">{current.items.map((item) => <div key={item.id} className="rounded-xl bg-slate-50 p-3 text-center dark:bg-slate-800"><div className="mb-2 text-3xl">{iconFor(item.type)}</div><div className="truncate text-sm font-medium text-slate-900 dark:text-white">{item.name}</div><div className="mt-0.5 text-xs text-slate-500">{typeLabels[item.type]} · {item.color}</div></div>)}</div>{current.warnings.length > 0 && <div className="mt-4 rounded-xl bg-amber-50 p-3 text-sm text-amber-800 dark:bg-amber-500/10 dark:text-amber-200"><div className="flex items-center gap-1.5 font-medium"><AlertTriangle size={15} />出行提醒</div>{current.warnings.map((warning) => <p key={warning} className="mt-1 text-xs leading-5">{warning}</p>)}</div>}<div className="mt-4 rounded-xl bg-sky-50 p-3 text-sm text-sky-900 dark:bg-sky-500/10 dark:text-sky-100"><span className="font-medium">AI 搭配理由：</span>{current.note}</div><div className="mt-4 grid grid-cols-2 gap-2 sm:grid-cols-4">{Object.entries(current.breakdown).map(([label, score]) => <div key={label} className="rounded-xl border border-slate-100 p-2 dark:border-slate-800"><div className="text-xs text-slate-500">{label}</div><div className="mt-1 text-sm font-semibold text-slate-900 dark:text-white">{Math.round(score)}<span className="text-xs font-normal text-slate-400"> / 100</span></div></div>)}</div></> : <p className="py-8 text-center text-sm text-slate-400">当前衣柜没有符合此场合的搭配。</p>}<AITrust source={source} degraded={degraded} reasons={current?.reasons ?? reasons} className="mt-4" /></div></Card>
    <Card><div className="border-b border-slate-100 p-4 dark:border-slate-800"><h2 className="text-sm font-semibold text-slate-900 dark:text-white">我的衣柜</h2></div><div className="grid grid-cols-2 gap-3 p-4 sm:grid-cols-3 lg:grid-cols-4">{mockWardrobeItems.map((item) => <div key={item.id} className="rounded-xl border border-slate-200 p-3 text-center transition hover:border-sky-300 dark:border-slate-800 dark:hover:border-sky-700"><div className="mb-2 text-3xl">{iconFor(item.type)}</div><div className="truncate text-sm font-medium text-slate-900 dark:text-white">{item.name}</div><div className="mt-1 text-xs text-slate-500">{item.color} · {typeLabels[item.type]}</div><div className="mt-2 flex flex-wrap justify-center gap-1">{item.style.slice(0, 2).map((style) => <Badge key={style} variant="info">{style}</Badge>)}</div></div>)}</div></Card></div>;
}
