"use client";

import { useState } from "react";
import { Check, ChevronDown, ExternalLink, Eye, RefreshCw, X } from "lucide-react";
import { useAgentOutputsData } from "@/hooks/useData";
import { useCockpit } from "@/hooks/useAI";
import { cardSubtitle, normalizeApproval, normalizeBrief, normalizeMessage, normalizeReport } from "@/lib/ai";
import { DataError, DemoBanner, EmptyState } from "@/components/shared/DataStates";
import type { AgentOutput } from "@/types";

const severity = { urgent: "border-rose-200 bg-rose-50 dark:border-rose-500/30 dark:bg-rose-500/10", attention: "border-amber-200 bg-amber-50 dark:border-amber-500/30 dark:bg-amber-500/10", info: "border-slate-200 bg-white dark:border-slate-800 dark:bg-slate-900" } as const;
const ago = (value: string | null) => { if (!value) return "尚未抓取"; const h = Math.max(0, Math.floor((Date.now() - Date.parse(value)) / 3600000)); return h < 1 ? "刚刚更新" : `${h} 小时前更新`; };

export default function CockpitPage() {
  const data = useAgentOutputsData(); const [handled, setHandled] = useState(false); const [expanded, setExpanded] = useState<string | null>(null); const view = useCockpit(data.items, { includeHandled: handled });
  return <div className="space-y-5"><DemoBanner isDemo={data.isDemo} /><DataError error={data.error} onRetry={() => void data.refresh()} />
    <section className="overflow-hidden rounded-3xl bg-slate-950 p-5 text-white shadow-xl dark:bg-slate-900 sm:p-7"><div className="flex flex-wrap items-start justify-between gap-4"><div><p className="text-xs font-semibold tracking-[0.18em] text-sky-300">WORK COCKPIT</p><h1 className="mt-2 text-2xl font-bold tracking-tight sm:text-3xl">{view.headline}</h1><p className="mt-2 text-sm text-slate-300">{ago(view.lastUpdated)} · {view.actionableCount} 件待跟进</p></div><button onClick={() => void data.refresh()} disabled={data.loading} className="inline-flex items-center gap-2 rounded-xl bg-white/10 px-3 py-2 text-xs font-semibold hover:bg-white/20 disabled:opacity-50"><RefreshCw size={15} className={data.loading ? "animate-spin" : ""} />刷新</button></div>{view.isStale && <div role="alert" className="mt-5 rounded-xl border border-amber-300/40 bg-amber-300/10 px-3 py-2 text-sm text-amber-100">数据可能已过期，让 WorkBuddy 跑一次抓取。</div>}</section>
    <label className="flex w-fit items-center gap-2 text-xs text-slate-500"><input type="checkbox" checked={handled} onChange={(e) => setHandled(e.target.checked)} className="rounded text-sky-600" />显示已处理</label>
    {!data.loading && data.items.length === 0 ? <EmptyState title="还没有数据。让 WorkBuddy 跑一次抓取即可。" /> : <div className="grid gap-4 xl:grid-cols-2">{view.sections.map((section) => <section key={section.kind} className="rounded-2xl border border-slate-200 bg-slate-50/70 p-3 dark:border-slate-800 dark:bg-slate-950/40"><header className="mb-3 flex items-center justify-between px-1"><h2 className="font-semibold text-slate-900 dark:text-white">{section.icon} {section.label}</h2><span className="text-xs text-slate-500">{section.items.length} 条{section.urgentCount > 0 && <b className="ml-2 text-rose-600">{section.urgentCount} 紧急</b>}</span></header>{section.items.length ? <div className="space-y-2">{section.items.map((item) => <OutputCard key={item.id} item={item} expanded={expanded === item.id} onExpand={() => setExpanded(expanded === item.id ? null : item.id)} onUpdate={(status) => void data.update(item.id, { status })} />)}</div> : <p className="rounded-xl border border-dashed border-slate-300 px-3 py-8 text-center text-sm text-slate-500 dark:border-slate-700">{section.emptyHint}</p>}</section>)}</div>}</div>;
}

function OutputCard({ item, expanded, onExpand, onUpdate }: { item: AgentOutput; expanded: boolean; onExpand: () => void; onUpdate: (status: "read" | "done" | "dismissed") => void }) {
  const detail = item.kind === "approval" ? <Approval detail={item.detail} /> : item.kind === "message" ? <Points points={normalizeMessage(item.detail).keyPoints} marker={normalizeMessage(item.detail).mentionedMe ? "@ 我" : undefined} /> : item.kind === "brief" ? <Points points={normalizeBrief(item.detail).keyPoints} marker={normalizeBrief(item.detail).needsReply ? "需回复" : undefined} /> : item.kind === "report" ? <Report detail={item.detail} /> : null;
  return <article className={`rounded-xl border p-3 ${severity[item.severity] ?? severity.info}`}><div className="flex gap-3"><button onClick={onExpand} className="min-w-0 flex-1 text-left"><div className="flex items-center gap-2"><h3 className="truncate text-sm font-semibold text-slate-900 dark:text-white">{item.title}</h3>{item.severity === "urgent" && <span className="rounded bg-rose-600 px-1.5 py-0.5 text-[10px] font-bold text-white">紧急</span>}</div><p className="mt-1 truncate text-xs text-slate-500">{cardSubtitle(item)}</p><p className="mt-2 text-sm text-slate-700 dark:text-slate-300">{item.summary}</p></button><div className="flex shrink-0 flex-col gap-1"><button onClick={() => onUpdate("read")} aria-label="已读" className="rounded p-1.5 text-slate-500 hover:bg-white"><Eye size={14} /></button><button onClick={() => onUpdate("done")} aria-label="完成" className="rounded p-1.5 text-emerald-600 hover:bg-white"><Check size={14} /></button><button onClick={() => onUpdate("dismissed")} aria-label="忽略" className="rounded p-1.5 text-slate-500 hover:bg-white"><X size={14} /></button>{item.action_url && <a href={item.action_url} target="_blank" rel="noreferrer" aria-label="打开原始位置" className="rounded p-1.5 text-sky-600 hover:bg-white"><ExternalLink size={14} /></a>}</div></div>{expanded && <div className="mt-3 border-t border-slate-200 pt-3 dark:border-slate-700">{detail}<button onClick={onExpand} className="mt-2 inline-flex items-center gap-1 text-xs text-sky-700 dark:text-sky-300">收起 <ChevronDown size={13} className="rotate-180" /></button></div>}</article>;
}
function Points({ points, marker }: { points: string[]; marker?: string }) { return <>{marker && <span className="rounded bg-sky-100 px-2 py-1 text-xs font-medium text-sky-700">{marker}</span>}<ul className="mt-2 space-y-1 text-sm text-slate-600 dark:text-slate-300">{points.map((point) => <li key={point}>• {point}</li>)}</ul></>; }
function Approval({ detail }: { detail: unknown }) { const x = normalizeApproval(detail); return <div className="space-y-2 text-sm"><p className="rounded-lg bg-sky-50 p-2 text-sky-900 dark:bg-sky-500/10 dark:text-sky-100"><b>AI 建议：</b>{x.aiSuggestion ?? "暂无建议"}</p>{x.aiConcerns.map((concern) => <p key={concern} className="rounded-lg bg-amber-50 p-2 text-amber-900 dark:bg-amber-500/10 dark:text-amber-100">注意：{concern}</p>)}</div>; }
function Report({ detail }: { detail: unknown }) { const x = normalizeReport(detail); return <table className="w-full text-left text-xs"><thead className="text-slate-500"><tr><th>负责人</th><th>事项</th><th>逾期</th></tr></thead><tbody>{x.pending.map((row) => <tr key={`${row.who}-${row.what}`} className="border-t border-slate-200 dark:border-slate-700"><td className="py-1.5">{row.who}</td><td>{row.what}</td><td className={row.overdueDays > 0 ? "font-semibold text-rose-600" : "text-slate-500"}>{row.overdueDays > 0 ? `${row.overdueDays} 天` : "—"}</td></tr>)}</tbody></table>; }
